### ISSUE TITLE
Compilation failure in Elixir 1.18 rc 0

### ISSUE THREAD

**Issue by nathany-copia** [parroty/exvcr#223]
```
==> exvcr
Compiling 32 files (.ex)
    error: recursive variable definition in patterns:

    start(arg = arg)

    the variable "arg" is defined in function of itself
    │
 13 │     defstart start(arg), do: initial_state(arg)
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │
    └─ lib/exvcr/actor.ex:13: ExVCR.Actor.Responses.start/1


== Compilation error in file lib/exvcr/actor.ex ==
** (CompileError) lib/exvcr/actor.ex: cannot compile module ExVCR.Actor.Responses (errors have been logged)
    (stdlib 6.2) maps.erl:860: :maps.fold_1/4
    lib/exvcr/actor.ex:13: (module)
```

**Comment by nathany-copia** [comment]
https://github.com/elixir-lang/elixir/releases/tag/v1.18.0-rc.0

**Comment by nathany-copia** [comment]
#223

**Comment by nathany-copia** [comment]
FYI https://elixir-lang.org/blog/2024/12/19/elixir-v1-18-0-released/

**Comment by nathany-copia** [comment]
As it turns out, ExVCR didn’t work in Elixir 1.18 release candidate, but it does work in Elixir 1.18.
